[tool.poetry]
name = "servidor-messenger"
version = "0.1.0"
description = ""
authors = ["Thales H. Nascimento <thales_henrique_n@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
